---
title: "Sector Coupling"
date : last-modified # now
author: 
 - name: "Jiseok AHN"
   affiliation: "KIER"
title-block-banner: true
format: 
  html:
    theme: flatly
    code-fold: true
    toc: true
   # toc-depth: 2
    toc-title: 목차
    number-sections : true
    #number-depth: 2
    highlight-style: github
    self-contained: false
bibliography: references.bib
---

# 23.08.25. 한국환경경제학회

## DIETER 모형을 활용한 전기차 섹터커플링의 환경 및 경제적 편익 산정(KEI 최형식)

1.  섹터커플링 효과 연구

-   섹터커플링 없이는 ESS 및 출력 제한이 증가, P2X를 통해 잉여 전력을 활용하고, ESS 대체 가능[@zerrahn2018]

-   적절한 섹터커플링 정책 없이 수송 및 열부분을 전력시스템과 토압 시 전력시스템 비용 급증. 수송부문에서는 전기차 수요반응 참여 및 V2G 정책 활용 필요.[@brown2018]

-   수송 및 열부문 섹터커플링을 통해 ESS 대체가 가능하며, 기타 수소 및 열저장 기술 투자 비용 절감 가능[@victoria2019]

2.  국내 스마트 충전 관련 연구

-   E-mobility 성장에 따른 석유·전력·신재생에너지 산업 대응 전략 연구(전력)[@gimdoweon]

-   전기차 충전의사결정 모형 기반 게시별 요금제에 대한 부하 이전 효과 평가

-   전기차 충전부하 피크는 19시에 가장 높을 것으로 전망

-   계시별 요금제 도입을 통해 부하 변동성 감소

# 관련 논문

## Modeling and simulation of Power-to-X systems: A review[@ince2021]

-   Introduction

    -   Today, the share of electricity generation from renewable energy resources is approximately 25% in the world, and it is forecasted that it will have a share of two-thirds of the electricity generation by 2040
    -   An important limitation of the use of RES is the fluctuating nature, which may lead to temporary surplus or lack of electricity and instability in the electric grid network. In this regard, energy storage technologies play an important role in providing a balance between supply and demand in the grid network at different time scales (seconds and subseconds, hourly, daily, and seasonally)
    -   The capacity of energy storage (e.g, hydrogen, batteries, pumped hydro and compressed air) has increased.
    -   Hydrogen (H2) is a promising energy carrier, which is versatile, transportable, clean (if produced from renewables), and has the highest gravimetric energy density among other alternatives, but its energy content per volume is comparatively low.
    -   Hydrogen was produced from natural gas through steam reforming (48%), from the petroleum fraction through steam reforming and partial oxidation (30%), and from coal through gasification (18%), while only about 4% were produced from water through electrolysis in the early 2010 s

-   Conclusions

    -   This study(reviews) aims to investigate, compare, and discuss the recent studies (between 2015 and 2020) on **thermodynamic**, **techno-economic**, and **life cycle assessments** of different P-t-X systems.
    -   (Thermodynamic analysis) the **SOE technology** in steam and co-electrolysis modes is the most preferable electrolyzer technology in the P-t-X systems, among the other electrolyzer types. SOE technology is preferred mainly due to its thermal integration compatibility with other subcomponents.
    -   (Thermodynamic analysis) the energy requirement for the CO2 capture process. **The membrane-integrated** P-t-X system gives better system performance thermodynamically among the other CO2 capture techniques
    -   **The methane production system** through the P-t-X concept is the most preferable technology due to fact the synthetic methane can be utilized in many industrial applications (heating, transport, and power production), and can be integrated into available gas transportation infrastructures.
    -   (Techno-economic assessment) **wind and solar** energy sources are the most preferable energy sources. It is also reported that **methanol, DME, and gasoline** are the favourable products in terms of economics, while `the cost of renewable ammonia production` is relatively higher.
    -   (Life cycle assessment) 18 different indicators are commonly used in the literature, and the most preferred indexes have been **GWI (Global Warming Impact)** and **GHG (Greenhouse Gas Emission)**.
    -   The physical adsorption techniques in the CO2 capture process are superior to the chemical absorption techniques in terms of life cycle assessment indicators.
    -   some `P-t-Methane systems` are more harmful in terms of some factors such as metal depletion, water depletion, and terrestrial, marine, and human toxicity compared to the conventional natural gas production system.

## Synergies of sector coupling and transmission reinforcement in a cost-optimised, highly renewable European energy system[@brown2018]

-   Introduction
    -   Many studies have been conducted for European electricity sector. But, focusing on the electricity sector means not only neglecting the significant greenhouse gas emissions from **other energy demand sectors, such as heating and transport**, but also ignoring **important sources of flexibility in these sectors**.
    -   Modelling all energy sectors in high spatial and temporal detail is computationally demanding. Studies of a few sectors have either considered just **electricity - heat**, **electricity - transport**, or **electricity - gas**.
    -   Studies that include multiple sectors, often encompassing all energy usage, but that sacrifice **spatial resolution** have typically either considered single countries or considered the whole continent of Europe without any spatial differentiation.
    -   In this paper both sector coupling and international grid integration are considered in the model **PyPSA-Eur-Sec-30**, the first open, hourly, country-resolved, sector-coupled investment model of the European energy system.
-   Conclusions
    -   The coupling of the heating and transport sectors to electricity in a European context enables both the consideration of a higher share (75%) of the total final energy usage in the model.
    -   The cost-optimal use of battery electric vehicles, synthetic electrofuels such as hydrogen and methane, heat pumps, district heating and long-term thermal energy storage removes the economic case for almost all stationary electricity storage and can reduce total system costs by up to 28%.
-   Policy Conclusions
    -   in cost-optimal energy systems with low emissions, wind and solar dominate primary energy generation, while heat pumps dominate heat provision.
    -   electrification of transport is more cost-effective than using synthetic fuels in transport because of efficiency losses when producing the fuels.
    -   The algorithms for managing battery electric vehicle charging should be exposed to dynamic electricity market prices.
    -   District heating in high-density, urban areas with long-term thermal energy storage can significantly reduce costs
    -   For heating systems with multiple technologies (heat pumps, resistive heating, solar thermal collectors and backup gas boilers for cold periods) can be efficient.
    -   Converting power to hydrogen and methane is advantageous in highly renewable systems, and the technologies for methanation and carbon dioxide capture should be developed further in view of this
    -   Finally, there are a variety of different possible paths to a highly renewable energy system, and no significant technical or economic barriers could be identified.

# 23.09.21 착수회의

-   회의비 집행 관련

    -   회의비는 외부인 있어야 집행 가능

    -   외부인 기업체 사람 넣는게 편하다...?

<!-- -->

-   연구목표

    -   섹터커플링 기술의 에너지 환경 측면의 파급효과 분석

    -   일반적인 섹터커플링 기술 뿐 아니라 연구단에서 개발하는 기술포함

    -   재생에너지 수용성 확대 측면의 분석 필요

    -   논문 쓰는 게 목표

-   분석범위

    -   고희상 박사님 경우 - 독립 실증 단지(JGRC)
    -   분산독립전원이면 장기가 아닌 단기
    -   제주도, 국가 단위라면 중장기

-   1단계 연구내용 : 모형 개발 - 섹터커플링 전반, 기술DB (문헌조사)

    -   1단계 상황에서 데이터를 받을 만한 게 별로 없다;;;. 우리가 역으로 수치를 도출해서 제시해야 할 것.

-   2단계 연구내용 : 모형 보완 (연구댄 개발 기술 상세화), 기술DB(연구단 개발 결과)

## P2X 전환 시나리오 개발 - 핵심 연구내용

-   P2X 전환 시나리오 개발 내용 및 절차

    -   기술 발전, 경제 및 정책 변화, 사회적 수용성 등 섹터커플링 전환에 영향을 미치는 다양한 요인 발굴

    -   요인별 미래 변화에 대한 합리적 가정 도출 및 정략적 지표화

    -   요인별 미래 전망치들에 대한 조합을 통해 다양한 섹터커플링 전환 시나리오 개발

    -   섹터커플링 파급효과 분석을 위한 시나리오로 활용 및 섹터커플링 사업화 촉진 \]및 기술 확산 보고서 작성에 활용

## 섹터커플링 파급효과 분석 - 핵심 연구내용

-   에너지시스템 모형 개발 및 파급효과 분석

    -   기존 기술 외에 미래 혁신 섹터커플링 기술까지 고려한 통합 분석이 가능한 에너지시스템 모형 개발

    -   타 융합과제의 실증연구결과를 활용할 수 있도록 에너지시스템 모형 상세화 수행

    -   섹터커플링 전환 시나리오별 에너지 환경 경제 측면의 다양한 파급효과 분석

    -   주요 요인들에 대한 민감도 분석을 통해 섹터커플링 보급 및 파급효과에 영향 미치는 요인 심층 분석

    ## 향후 추진 계획

    ::: callout-note
    -   전자 연구 노트 신청

    <!-- -->

    -   1차년도 업무분장 및 세부 추진계획 수립

        -   개인별 업무 구분 - 행정 업무 포함

        -   자체 연구 및 용역/자문 추진 업무 구분

        -   2주 단위 세부 추진계획 수립

    -   

    -   w
    :::

# 23.10.04 2차 회의

-   용역 2천만원으로 세 군대로 나눠서 진행

-   기후실에서 용역사 추천 받을 예정이며, 미팅 추진 필요

# 23.10.05\_ 전력수급 여건 변화와 대응과제

## 에너지원으로서 전기의 특성

-   **생산과 소비가 동시에 발생**. 수요-공급 불일치시 계통불안으로 광역정전 발생 가능. 정확한 수요예측과 충분한 발전력을 바탕으로 정밀한 실시간 수급관리 필요

-   **대규모 저장이 곤란.** 석유/석탄/가스 등 화석연료는 비축이 가능하기에 비상시 재고 활용. 전기를 저장하는 ESS는 기술여건과 경제성이 아직 부족

-   수요와 공급이 **비탄력**

    -   **전력수요의 비탄력성**: 요금이 올라도 쓸 수 밖에 없음. 다른 에너지원으로 대체가 곤란하며, 한번 전기를 사용하기 시작한 소비자는 계속 사용(ex.에어컨)

    -   **전력공급의 비탄력성**: 가격이 올라도 당장 더 만들기는 어려워. 설비 건설에 장기 기간이 소요(LNG 6년, 양수 10년, 대형 송전선로 13년, 해상풍력/원전 ??). 막대한 건설비. 1GW 용량 발전소 건설시 1\~3조원 소요 추정

## 전력수급기본계획

-   수립근거와 성격

    -   법적근거 : 전기사업법 제25조

    -   수립주기 : 매2년마다 수립(전기사업법 시행령 제15조)

    -   계획기간 : 15년(ex. 10차 전력수급기본계획 : 2022\~2036)

-   계획의 내용과 성격

    -   주요 내용 : 수요 공급 장기전망, 발전송전 설비계획, 수요관리, 온실가스 감축방안 등

    -   목표계획 : 수급전망, 설비계획, 적정예비율, 발전량믹스 등 정책방향 제시

    -   실행 계획 : 신규 발전설비 건설을 위한 허가의 근거

-   수요예측과 발전원 구성

    -   수요예측 : 미래의 전력수요(소비량, 최대전력) 예측. 다양한 변수 고려. 경제성장률, 인구변화 전망, 산업구조와 생활양식 변화, 기후변화 등

    -   발전원의 구성 : 예측된 수요를 바탕으로 필요설비 도출. 미래에 필요한 발전원의 종류와 용량 결정. 안정성, 경제성, 환경성 등 고려

-   제10차 전력수급기본계획('23.1.12)

    -   제8차, 제9차 전기본 : 탈워전 및 탈석찬, 신재생 중심의 에너지 전환

    -   제10차: 실현 가능하고 균형잡힌 전원믹스, 원전 활용, 적정 수준의 재생에너지

## 최근 전력수급 여건 변화

-   **전력수요** 여건 변화

    -   첨단산업 신규투자 확대 : 반도체, 바이오, 이차전지 등\<국가첨단산업 육성전략\> 발표('23.3). 대규모 신규투자 계획

        -   용인 시스템 반도체 첨단산단 등 전력 다소비 첨단산업 투자로 전력수요 증가 예상

        -   용인 반도체 산단 전력수요 10GW 내외 전망. 현재 수도줜 최대 전력수요(40GW)의 1/4 수준

    -   데이터 센터 증가: 국내 데이터센터 건설 의향은 계속 증가 추세

        -   AI기반 플랫폼( Chat GPT 등), 메타버스 등 IT 산업 확대 감안시 수요 증가요인 상당

    -   전기화에 따른 전력수요 증가

        -   화석연료를 사용하던 기술과 공정을 전기를 사용하도록 변환시키는 과정

        -   전기화에 따른 전력수요를 어느정도로 평가할지에 따라 장기 전력수요 전망에 편차 발생

-   **전력공급** 여건 변화

    -   신재생에너지 보급 상황

        -   주민수용성 문제, 계통연결 지연 등으로 신규설비 보급이 다소 둔화되는 추세

        -   제10차 전력수급기본계획 신재생 목표 달성을 위해서는 연 5GW 이상의 보급 필요

        -   발전사업의 실현가능성과 전력공급 기여도를 점검하여 현실성 있는 중장기 전망 제시 필요

    -   수소 발전 본격 추진

        -   10차 전력수급기본계획: 수소-LNG 혼소, 석탄-암모니아 혼소 반영

        -   수소발전 입찰시장 개설('23.6월): 일반수소(연료전지 중심), 청정수소(혼소발전 중심). 일반시장 입찰시장은 '25년부터, 청정수소 발전시장은 '27년부터 상업운전 개시

        -   혼소발전기 신규건설 혹은 대체건설(노후 LNG등 대체), 대체건설 대상 발전기 선정 등 필요

    -   국가온실가스감축폭표(NDC) 상향

        -   \<국가 탄소중립 녹색성장 기본계획\> 수립('23.4) : 전환부문 2030년 NDC 4백만톤 상향

        -   무탄소전원(Carbon free energy)의 발전비중 상향 필요. 원전, 해상풍력 등 건설에 장기 소요되는 전원은 활용이 어려운 측면. 태양광, 육상풍력, 재생e 또는 수소발전 확대가 불가피하나, 어느 하나만 택하기엔 곤란

## 정책과제와 추진 방향

-   향후 전력수급계획의 과제

    -   상충관계에 있는 에너지정책 목표의 합리적 조화 추구

        -   전력공급의 안정성을 최우선으로 하되, 경제성과 탄소중립 등 다른 중요 목표도 조화

    -   경직성/변동성 전원을 보완하는 유연성 전원 적정 확보

        -   탄소중립 추구에 따라 출력조정이 어려운 재생e 확대가 불가피(경직성 전원)

        -   재생e 확대시 기상상황에 따라 간헐성으로 수급 불안 요인 증가(변동성 전원)

        -   양수발전, ESS 등 유연선 전원을 적정 확보하면서 경직성 전원의 유연화 필요

-   **제11차 전력수급기본계획 추진 방향**

    -   미래 산업발전과 전기화를 감안한 과학적 수요 산정

        -   첨단산단과 데이터센터 등 수요확대 요인이 미칠 영향을 평가하여 수요전망에 반영

        -   기술개발 전망 등을 감안하여 전기화 수요 정밀 반영

        -   ***제10차 전력수급기본계획의 경우 기술개발의 불확실성을 감안하여, 모형 도출 결과의 일부만 반영 --\> 11차도 그렇게 하지 않을까??***

    -   전원별 특성을 고려한 입체적 전원믹스 구성

        -   무탄소 전원을 지속 보급하되, 기술발전 등을 감안하여 안정성 보완방안 마련

        -   실현가능한 재생E보급목표 반영하고, 노후 화력발전설비 활용방안(혼소발전 등) 검토 필요

    -   스마트하고 유연한 전력시스템 구축

        -   적정한 규모의 유연성 자원을 확충하여 어떤 상황에도 대응 가능한 전력시스템 구축

        -   IT 기술을 활용한 수요반응자원(DR) 활성화, 화력발전 유연성 향상, 재생e 예측력 제고 등 추진

# 23.10.16 기후테크2023

## 발표자료

-   [발표자료](https://github.com/coreanjs/energy-data/blob/master/2023_%EA%B8%B0%ED%9B%84%ED%85%8C%ED%81%AC_%EC%9E%90%EB%A3%8C%EC%A7%91(%EC%9B%B9%EC%9A%A9).pdf)는 여기서 다운로드

## 서울대 정수종 교수 발표

-   기후변화는 지구 기온 상스으로 인해 발생한 결과. 공기중에 탄소가 너무 많이 늘어났기 때문에 기후가 변하였고, 탄소를 줄여야 할 때임. 탄소는 왜 늘었나? 문명의 발달에 따른 탄소 배출량 증가.

-   기후테크란 온실가스 감축과 기후적응에 기여하는 모든 혁신기술을 의미함. 수익을 창출할 수 있는 분야여야 함. 현재 5개 분야로 구분되어있으며, 탄녹위에서 분류한 것.

-   기후테크 산업분야 확대. 코로나로 인해 기술 투자는 위축되었지만 기후테크 분야는 위축되지 않을 것.

-   기후테크 고려사항 'K-Taxonomy'. 감축도 중요하지만 적응기술도 중요함. 감축과 적응을 둘 다 고려해야하고, 좋은 기술일지라도 수자원을 훼손하거나, 생물다양성을 훼손하는 기술들을 주의해야 함. 한국 뿐 아니라 세계적인 추세임(적응을 함께 고려하는 것). 둘 다 만족시켜야 함.

-   서울대 기후테크센터, 2023년 4월 서울대 국가지정연구소로 승인 및 설립. 기후테크 포럼, 교육, 컨설팅 등.

## 산업통상자원부 에너지기술과 홍수경 과장

-   기후테크산업 육성전략. 지난 6월 총리 주재 발표된 안건으로 만든 것임. 탄녹위 등 관계부처 협업으로 정책을 만들었고, 2\~3개월 작업 후 부처에서 할 수 있는 일들을 발굴하고, 시급한 일, 중장기적으로 해야 할 일을 나눠서 살펴봄.

### 추진배경

-   기후테크산업: 클린, 푸드, 에코, 카본, 지오 테크로 구분. 클린, 카본 테크가 에너지와 관련된 분야임.

-   기후테크 산업에 대한 전세계적 투자 확대. 전세계 3천건 넘는 투자와 701억 달러 이상('22년)

-   국내 기후테크 산업은 매출 및 고용 측면에서 타 산업 대비 높은 증가율 시현. 전체적인 규모는 큰 편이 아님.

-   국내 기후테크 기업은 10,065개로 에너지관련 분야가 90.8% 정도. 대부분.

-   시장. '21년 기후테크 산업 매출액은 약 200조원, '22\~'32년 10년간 연평균 상승률 24.2% 전망(세계)

### 현황 및 평가

-   \[낮은 기술수준\] 기술수준 미국 EU 대비 70-80% 수준 kisteep, 2020.

-   \[투자성과 미흡\] 위탁형 정책펀드를 통한 투자 지원에 한계. 민간투자 금융 연계 미흡.

-   \[시장진출 난항\] 규제 제도 개선, 성능 검증 절차 마련 필요.신속한 사업화 지원 미흡.

-   \[정책기반 미비\] 기후테크 산업 분류체계 미구축. 융복합 기술전문가 부족.

### 정책과제

-   \[투자\] 기후테크 산업 성장 지원펀드 조성 확대. 스케일업을 위한 기후금융 지원 강화

    -   (정책펀드 신설) 기후테크에 투자하는 4천억원 이상의 정책펀드 조성

    -   (ESG 투자 활성화) 정책펀드와 기업형 벤처캐피탈 투자 매칭, ESG 공시 및 활동 인증과연계한 민간 투자 활성화

-   \[시장\] 혁신조달을 활용한 초기수요 견인. 규제혁신을 통한 조속한 사업화 지원. 기후테크 산업의 수출동력화 촉진

    -   조달연계 사업화, 방위산업 연계, 특구 산단 연계 강화, 덩어리 규제 혁신

    -   공공브랜드 지원, 국제기구 협력 강화, 글로벌 그린허브 코리아GGHK

-   \[산업기반\] 민간 주도의 자발적 탄소시장 활성화. 기후테크 전문인력 양성 확대.

    -   인증표준 및 지침 고도화, 온실가스 감축사업 컨설팅 지원, 운영기반 구축, 기후테크 분류체계

### 기후테크 투자 동향 - 인비저닝 파트너스 제현주

-   2017년부터 옐로우독?으로 시작하였고, 2020년부터 기후테크 분야를 최우선 순위로 삼아 국내 대기업들과 기후테크에만 투자하는 700억원대 펀드 구성 후 투자중.

-   The future will be defined by the decoupling of carbon emission and GDP growth

-   글로벌 기업의 65%가 기후 및 지속가능성을 기업에게 가장 중요한 것 세가지 중 하나로 뽑음. 옳은 일이고 도덕정당위가 아니라, 자본시장에서 합리적인 이유도 포함됨.

-   기후변화 대응을 위한 혁신은 예상보다 빨리 오고 있고, 그 속도는 더욱 빨라질 것임.

-   지속가능성 혁신의 전제는 넷제로를 달성하면서, 이를 통해 사업의 성장을 일궈내는 것이며, 여기에는 기술 혁신이 필요함.

-   미국 유수의 기업 및 투자자들이 기후테크에 큰 돈을 걸기 시작.

-   기후테크 상업화를 위해서는 더 많은, 다른 속성의 자본이 필요. 소비가자 개인이 아닌 기업이나 정부인 경우가 많고, 하드웨어가 필요한 경우가 많다. 스케일업을 위해 차곡차곡 이력을 쌓아서 리스크를 업애야 함.

-   극복해야 할 과제.

    -   규모화를 위한 자본 부족. '전략적 속성의 명과 암. Equity 유지 외의 선택지 부족.

    -   인재풀의 다양성과 크기 부족. 창업자의 모수 절대적 부족. 글로벌 관점, 기술 전문성, 비즈니스 관점.

    -   다제적, 다원적 협력 부족. 학계-산업-금육-공공간 silo

    -   수요과 공급의 미스매치. 필요가 아니라 리스크로 투자 영역 결정.

### 자발적 탄소시장VCM 소개 - 대한상의 김녹영

-   자발적 탄소시장의 중요성.

-   VCM 글로벌 성장 현황 VCM 크레딧 발향규모는 최근 5년간 연펴균 30% 이상 성장 중

-   글로벌 탄소시장 동향. 규제시장과 자발적시장으로 구분, 최근 연계사례 증가, "콜롬비아-남아공 ETS, 싱가포르 탄소세, CORSIA등 VCM 활용". 파리협정 발표 후 시장 경계 모호해지는 추세.

-   VCM인증센터 및 거래 플랫폼 현황. VCM은 미국 등 주도 하에 인증 및 거래플랫폼 생태계 구축 진행

-   탄소갑축인증센터 소개
